"""initial_schema

Revision ID: ab340192086e
Revises: 
Create Date: 2026-03-17 22:13:34.475970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab340192086e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('igrejas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=False, comment='MATRIZ | CONGREGACAO'),
    sa.Column('igreja_mae_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['igreja_mae_id'], ['igrejas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_igrejas_igreja_mae_id'), 'igrejas', ['igreja_mae_id'], unique=False)
    op.create_table('tipos_evento',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor', sa.Text(), nullable=True, comment='Hex color, ex: #FF5733'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('igreja_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departamentos_igreja_id'), 'departamentos', ['igreja_id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.Text(), nullable=True),
    sa.Column('visibilidade', sa.Text(), nullable=False, comment='GERAL | POR_DEPARTAMENTO | POR_MINISTERIO | POR_MEMBRO'),
    sa.Column('e_recorrente', sa.Boolean(), nullable=False),
    sa.Column('data_hora_inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('igreja_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_evento_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tipos_evento.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_igreja_id'), 'eventos', ['igreja_id'], unique=False)
    op.create_index(op.f('ix_eventos_tipo_evento_id'), 'eventos', ['tipo_evento_id'], unique=False)
    op.create_table('membros',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.Text(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telefone', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False, comment='ATIVO | EM_OBSERVACAO | DESLIGADO'),
    sa.Column('igreja_principal_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['igreja_principal_id'], ['igrejas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membros_email'), 'membros', ['email'], unique=False)
    op.create_index(op.f('ix_membros_igreja_principal_id'), 'membros', ['igreja_principal_id'], unique=False)
    op.create_table('ministerios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('igreja_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ministerios_igreja_id'), 'ministerios', ['igreja_id'], unique=False)
    op.create_table('evento_departamento',
    sa.Column('evento_id', sa.BigInteger(), nullable=False),
    sa.Column('departamento_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id', 'departamento_id')
    )
    op.create_table('evento_membro',
    sa.Column('evento_id', sa.BigInteger(), nullable=False),
    sa.Column('membro_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id', 'membro_id')
    )
    op.create_table('evento_ministerio',
    sa.Column('evento_id', sa.BigInteger(), nullable=False),
    sa.Column('ministerio_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministerio_id'], ['ministerios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id', 'ministerio_id')
    )
    op.create_table('evento_ocorrencia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.BigInteger(), nullable=False),
    sa.Column('data_hora_inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('nota_ocorrencia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_ocorrencia_evento_id'), 'evento_ocorrencia', ['evento_id'], unique=False)
    op.create_table('evento_recorrencia',
    sa.Column('evento_id', sa.BigInteger(), nullable=False),
    sa.Column('frequencia', sa.Text(), nullable=False, comment='DAILY | WEEKLY | MONTHLY'),
    sa.Column('intervalo', sa.Integer(), nullable=False),
    sa.Column('dias_semana', sa.ARRAY(sa.Integer()), nullable=True, comment='0=Dom,1=Seg,...,6=Sab'),
    sa.Column('dias_mes', sa.ARRAY(sa.Integer()), nullable=True, comment='1-31'),
    sa.Column('posicao_na_semana', sa.Integer(), nullable=True, comment='1=primeiro, 2=segundo, -1=último'),
    sa.Column('dia_semana_posicao', sa.Integer(), nullable=True, comment='0=Dom,...,6=Sab — usado com posicao_na_semana'),
    sa.Column('data_fim', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ocorrencias_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id')
    )
    op.create_table('membro_departamento',
    sa.Column('membro_id', sa.BigInteger(), nullable=False),
    sa.Column('departamento_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membro_id', 'departamento_id')
    )
    op.create_table('membro_ministerio',
    sa.Column('membro_id', sa.BigInteger(), nullable=False),
    sa.Column('ministerio_id', sa.BigInteger(), nullable=False),
    sa.Column('funcao', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministerio_id'], ['ministerios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membro_id', 'ministerio_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('perfil', sa.Text(), nullable=False, comment='ADMIN | MEMBRO'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('membro_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_membro_id'), 'usuarios', ['membro_id'], unique=False)
    op.create_table('escala_ministerio_ocorrencia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('evento_ocorrencia_id', sa.BigInteger(), nullable=False),
    sa.Column('ministerio_id', sa.BigInteger(), nullable=False),
    sa.Column('membro_id', sa.BigInteger(), nullable=False),
    sa.Column('papel', sa.Text(), nullable=True, comment='Ex: líder de louvor, músico, intercessor'),
    sa.Column('status', sa.Text(), nullable=False, comment='PENDENTE | CONFIRMADO | CANCELADO | SUBSTITUTO'),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_ocorrencia_id'], ['evento_ocorrencia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministerio_id'], ['ministerios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escala_ministerio_ocorrencia_evento_ocorrencia_id'), 'escala_ministerio_ocorrencia', ['evento_ocorrencia_id'], unique=False)
    op.create_index(op.f('ix_escala_ministerio_ocorrencia_membro_id'), 'escala_ministerio_ocorrencia', ['membro_id'], unique=False)
    op.create_index(op.f('ix_escala_ministerio_ocorrencia_ministerio_id'), 'escala_ministerio_ocorrencia', ['ministerio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escala_ministerio_ocorrencia_ministerio_id'), table_name='escala_ministerio_ocorrencia')
    op.drop_index(op.f('ix_escala_ministerio_ocorrencia_membro_id'), table_name='escala_ministerio_ocorrencia')
    op.drop_index(op.f('ix_escala_ministerio_ocorrencia_evento_ocorrencia_id'), table_name='escala_ministerio_ocorrencia')
    op.drop_table('escala_ministerio_ocorrencia')
    op.drop_index(op.f('ix_usuarios_membro_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('membro_ministerio')
    op.drop_table('membro_departamento')
    op.drop_table('evento_recorrencia')
    op.drop_index(op.f('ix_evento_ocorrencia_evento_id'), table_name='evento_ocorrencia')
    op.drop_table('evento_ocorrencia')
    op.drop_table('evento_ministerio')
    op.drop_table('evento_membro')
    op.drop_table('evento_departamento')
    op.drop_index(op.f('ix_ministerios_igreja_id'), table_name='ministerios')
    op.drop_table('ministerios')
    op.drop_index(op.f('ix_membros_igreja_principal_id'), table_name='membros')
    op.drop_index(op.f('ix_membros_email'), table_name='membros')
    op.drop_table('membros')
    op.drop_index(op.f('ix_eventos_tipo_evento_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_igreja_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_departamentos_igreja_id'), table_name='departamentos')
    op.drop_table('departamentos')
    op.drop_table('tipos_evento')
    op.drop_index(op.f('ix_igrejas_igreja_mae_id'), table_name='igrejas')
    op.drop_table('igrejas')
    # ### end Alembic commands ###
